### ISSUE TITLE
Livewire 3.4.11 + Powergrid Cannot Detect Alpine

### ISSUE THREAD

**Issue by killallskywalker** [Power-Components/livewire-powergrid#1527] opened 2024-05-03 22:45 UTC
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes 
![Screenshot 2024-05-04 at 6 42 31 AM](https://github.com/Power-Components/livewire-powergrid/assets/19742186/c172a5f1-f8e1-45ac-8d68-e1d5212c5b56)

### PHP Version

8.2.18

### PowerGrid

5.4.10

### Laravel

10.48.7

### Livewire

 3.4.11 

### Alpine JS

3.13.8

### Theme

Bootstrap

### Describe the bug.

im trying to use editOnClick and filter . However i just got all the error as in screenshot . Since latest livewire it alredy preload alpine , im not sure in the case of powergrid do we need to import on our own ?

### To Reproduce...

Just pick the bootstrap 5 theme .

**Comment by killallskywalker** [comment] 2024-05-09 06:16
Im tyring to check if the problem lie to my alpine setup . however another alpine component are working well in the same page where the table are use .

**Comment by luanfreitasdev** [comment] 2024-05-09 12:03
Hi, have you tested this with the latest version of livewire?

**Comment by killallskywalker** [comment] 2024-05-13 23:33
Hi @luanfreitasdev , yes just upgrade it to the latest one which is v5.6.0

**Comment by killallskywalker** [comment] 2024-05-14 00:21
Ill bump it to 5.6.2 . However it still have the same issue where alpine expression is not defined . Is it this might related to how i build the assets also ? @luanfreitasdev

**Comment by luanfreitasdev** [comment] 2024-05-14 14:14
I can't reproduce this problem, the powergrid demo contains the latest updates:
https://demo.livewire-powergrid.com/examples/validation

Did you follow these? https://livewire-powergrid.com/get-started/powergrid-configuration.html#essential-configuration

**Comment by killallskywalker** [comment] 2024-05-22 01:08
@luanfreitasdev yeap have been following this . Let me check back because currently im using bootstrap template that already have their own library  . It could be the conflict with the npm library  . Let me check and will update here .  But based on the demo look like it not the powergrid problem .

**Comment by luanfreitasdev** [comment] 2024-05-25 16:29
Hello!. So I'm going to close this issue. If you discover the problem, you can report it here. thanks!

**Closed as completed by luanfreitasdev** 2024-05-25 16:29 UTC
Labels: need more info
