### ISSUE TITLE
  Unable to locate a class or view for component [livewire-powergrid::actions-header].

### ISSUE THREAD

**Issue by zxtanzxzx** [Power-Components/livewire-powergrid#1160] opened 2023-09-19 00:32 UTC
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Unable to locate a class or view for component [livewire-powergrid::actions-header].

![image](https://github.com/Power-Components/livewire-powergrid/assets/12552846/f084366b-6814-4b16-8edc-123336cc1291)

### PHP Version

8.1.21

### PowerGrid

v5.0.7

### Laravel

10.23.1

### Livewire

3.0.5

### Theme

Tailwind 3.x

### Describe the bug.

Install powergrid and try to run view::cache command and encounter this erorr. 
Tried in a multiple projects, both run in linux and windows. Same error presented after running  php artisan view:cache.

### To Reproduce...

Run` php artisan cache:view `

**Comment by ermakk** [comment] 2023-10-08 08:42
Получилось решить проблему?

**Comment by luanfreitasdev** [comment] 2023-10-09 13:07
I've never been able to reproduce this. Was this from a new installation or upgrade? If it is an upgrade, you must republish all views (if any), as they are incompatible.

**Comment by CrazyBoy49z** [comment] 2023-10-12 17:58
@luanfreitasdev 

This problem occurs both during a new installation and when updating the project. At first I thought that the problem was after the update. But on a new project, after installing power-grid, the same problem occurred

While I do not understand why it occurs, there will be time to look for why

**Comment by CrazyBoy49z** [comment] 2023-10-12 18:20
@luanfreitasdev component reference error

https://github.com/Power-Components/livewire-powergrid/blob/5.x/resources/views/components/frameworks/tailwind/actions.blade.php#L3

<img width="817" alt="image" src="https://github.com/Power-Components/livewire-powergrid/assets/3448603/03aca374-32aa-4428-b668-7fc9124aa2c8">

**Comment by luanfreitasdev** [comment] 2023-10-14 12:51
Fixed by @CrazyBoy49z .

**Closed as completed by luanfreitasdev** 2023-10-14 12:51 UTC
Labels: need more info
