### ISSUE TITLE
Return type of dataSource() error

### ISSUE THREAD

**Issue by edwinheij** [Power-Components/livewire-powergrid#44] opened 2021-08-10 08:20 UTC
Return value of App\Http\Livewire\ProductTable::dataSource() must be an instance of App\Http\Livewire\Collection, instance of Illuminate\Database\Eloquent\Collection returned

**Comment by luanfreitasdev** [comment] 2021-08-20 20:34
Hi @edwinheij 

I couldn't reproduce the same error. Can you specify the situation better?

I will close the issue, but if it happens again, you can reopen it again.

Hug.

**Closed by luanfreitasdev** 2021-08-20 20:34 UTC
