### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Elshaden** [Power-Components/livewire-powergrid#87] opened 2021-10-28 12:50 UTC
Thanks for this great add on

I think that the table is not responsive, meaning when viewed in different size screen, it goes off screen without scrolling either side .

is this the case?

**Comment by luanfreitasdev** [comment] 2021-11-03 22:14
I'm going to close this issue because I couldn't understand better what the problem is.

**Closed by luanfreitasdev** 2021-11-03 22:14 UTC
