### ISSUE TITLE
When searching a row and then deleting search input last <td> element is not generated

### ISSUE THREAD

**Issue by pauleniz** [Power-Components/livewire-powergrid#225] opened 2022-01-13 14:05 UTC
First of all, did you see if your problem has happened to other people before?
- [x] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**
When searching for exact row and then deleting the input value of the search filter, the last <td> element of the row that was searched is not generated.
I changed the bootstrap theme to match my project theme but with the Tailwind theme that was not changes same bug happens.
Even if the table has only one basic column without a callback function same bug happens.
* 

**To Reproduce**
I have no idea how to reproduce it I use powergrid version 2.0.0 just created table and performed the search and then deleted the input

**Laravel version (exactly)** 
8.40
*

**Livewire version (exactly)**
2.5
*

**AlpineJS:** 
3.x.x form powergrid-config
*

**Theme:**
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [x] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)
Step 1 table with the data and search input is empty:
![image](https://user-images.githubusercontent.com/65357711/149343516-41efd5fc-180c-4c5b-aca5-cf658500e99e.png)

Step 2 I search exact row:
![image](https://user-images.githubusercontent.com/65357711/149343723-664b308d-dfed-414a-83d2-b37c1a6995a2.png)

Step  3 I delete search input value and last <td> element of that searched row is gone:
![image](https://user-images.githubusercontent.com/65357711/149343925-90d86920-9c17-44cf-a4d4-3b05ff847c22.png)

If I delete search input slowly 1 letter at the time and let it refresh it looks like this:
Deleted search input ( changed from 10 to 1)
![image](https://user-images.githubusercontent.com/65357711/149344174-395aaed6-ee7c-42b5-9da4-bb5692f42f6d.png)
Deleted search input ( changed from 1 to '')
![image](https://user-images.githubusercontent.com/65357711/149344349-346b0c67-415d-478a-aff1-346e7da988ce.png)

**Do you have any idea how we can fix it?**
Tried looking into it but couldn't find anything

**Put part of your code, an html screenshot of the problem element:**
The last <td> element is not even generated.
![image](https://user-images.githubusercontent.com/65357711/149344514-235949fc-ea0e-4247-84e1-32b4419a197e.png)

**Comment by luanfreitasdev** [comment] 2022-01-16 00:25
Hello, thank you very much for the explanation, I also believe that, I will close this issue.

**Comment by luanfreitasdev** [comment] 2022-01-29 12:12
Unfortunately I couldn't reproduce this problem, if you can update to the latest version and test it again. For now I will close it.

Thanks

**Closed by luanfreitasdev** 2022-01-29 12:12 UTC
Labels: bug
