### ISSUE TITLE
[Bug]: Column not found when sorting on DB::raw column and export

### ISSUE THREAD

**Issue by AmirAghaee** [Power-Components/livewire-powergrid#1033] opened 2023-06-19 08:27 UTC
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

v4.8.0

### Laravel

10.13.5

### Livewire

2.12.3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

After sorting on the raw column and exporting, I get an error!

![datasource](https://github.com/Power-Components/livewire-powergrid/assets/22327627/92e933c9-6b92-4666-a901-978a375739f2)

![column](https://github.com/Power-Components/livewire-powergrid/assets/22327627/582d67dc-9d15-49a7-bbee-732f2f9d3a19)

![error](https://github.com/Power-Components/livewire-powergrid/assets/22327627/a287af6e-557e-43bc-a6ab-04424523bd9a)

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php

final class ContentsTable extends PowerGridComponent
{
    use WithExport, Actions, ActionButton;

    public string $primaryKey = 'contents.id';

    public string $sortField = 'contents.id';

    public string $sortDirection = 'desc';

    protected function getListeners(): array
    {
        return array_merge(
            parent::getListeners(),
            [
                'deleteDialog',
            ]
        );
    }

    public function setUp(): array
    {
        $this->persist(['columns', 'filters']);

        $this->showCheckBox();

        return [
            Exportable::make('export')->striped()->type(Exportable::TYPE_XLS, Exportable::TYPE_CSV),
            Header::make()->showSearchInput()->showToggleColumns(),
            Footer::make()->showPerPage()->showRecordCount()->showPerPage(25, [0, 5, 10, 25, 50]),
        ];
    }

    public function datasource(): Builder
    {
        return Content::query()
            ->with('publishers')
            ->with('subject_headings')
            ->with('tags')
            ->select([
                'contents.id',
                'contents.title',
                'contents.isbn',
                'contents.publication_year',
                'contents.correspondent_description',
                'contents.page_number',
                'contents.read_time_min',
                'contents.is_published',
                'contents.storage_id',
                'contents.ten_percent_book_id',
                'contents.is_free',
                DB::raw("
                      (SELECT count(*)
                      FROM `users_contents`
                      WHERE `contents`.`id` = `users_contents`.`content_id` and
                       (`users_contents`.`status` = 'reading' or `users_contents`.`status` = 'finished')
                       )
                      AS `reading_count`
                    ")
            ]);
    }

    public function relationSearch(): array
    {
        return [
            'Publishers' => [
                'title'
            ]
        ];
    }

    public function addColumns(): PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('id')
            ->addColumn('title')
          
            ->addColumn('reading_count');
    }

    public function columns(): array
    {
        return [
            Column::make('ID', 'id')
                ->searchable()
                ->sortable(),

            Column::make('عنوان', 'title')
                ->searchable()
                ->sortable(),

            Column::make('تعداد مطالعه کتاب', 'reading_count', 'reading_count')
                ->sortable(),
        ];
    }

    
}
```

**Comment by luanfreitasdev** [comment] 2023-06-22 19:56
Hello, can you share your Flare?

**Comment by AmirAghaee** [comment] 2023-06-25 07:32
```
[2023-06-25 10:59:10] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'contents.reading_count' in 'order clause' (Connection: mysql, SQL: select `contents`.`id`, `contents`.`title`, `contents`.`isbn`, `contents`.`publication_year`, `contents`.`correspondent_description`, `contents`.`page_number`, `contents`.`read_time_min`, `contents`.`is_published`, `contents`.`storage_id`, `contents`.`ten_percent_book_id`, `contents`.`is_free`, 
                      (SELECT count(*)
                      FROM `users_contents`
                      WHERE `contents`.`id` = `users_contents`.`content_id` and
                       (`users_contents`.`status` = 'reading' or `users_contents`.`status` = 'finished')
                       )
                      AS `reading_count`
                     from `contents` where `contents`.`deleted_at` is null order by `contents`.`reading_count` desc) {"userId":156,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'contents.reading_count' in 'order clause' (Connection: mysql, SQL: select `contents`.`id`, `contents`.`title`, `contents`.`isbn`, `contents`.`publication_year`, `contents`.`correspondent_description`, `contents`.`page_number`, `contents`.`read_time_min`, `contents`.`is_published`, `contents`.`storage_id`, `contents`.`ten_percent_book_id`, `contents`.`is_free`, 
                      (SELECT count(*)
                      FROM `users_contents`
                      WHERE `contents`.`id` = `users_contents`.`content_id` and
                       (`users_contents`.`status` = 'reading' or `users_contents`.`status` = 'finished')
                       )
                      AS `reading_count`
                     from `contents` where `contents`.`deleted_at` is null order by `contents`.`reading_count` desc) at /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Connection.php:795)
[stacktrace]
#0 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\\Database\\Connection->run()
#2 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2735): Illuminate\\Database\\Connection->select()
#3 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2724): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3278): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2723): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#6 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(717): Illuminate\\Database\\Query\\Builder->get()
#7 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(701): Illuminate\\Database\\Eloquent\\Builder->getModels()
#8 /var/www/boom/vendor/power-components/livewire-powergrid/src/Traits/WithExport.php(185): Illuminate\\Database\\Eloquent\\Builder->get()
#9 /var/www/boom/vendor/power-components/livewire-powergrid/src/Traits/WithExport.php(236): App\\Http\\Livewire\\admin\\contents\\ContentsTable->prepareToExport()
#10 /var/www/boom/vendor/power-components/livewire-powergrid/src/Traits/WithExport.php(195): App\\Http\\Livewire\\admin\\contents\\ContentsTable->export()
#11 /var/www/boom/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Http\\Livewire\\admin\\contents\\ContentsTable->exportToXLS()
#12 /var/www/boom/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/boom/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /var/www/boom/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /var/www/boom/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(149): Illuminate\\Container\\BoundMethod::call()
#16 /var/www/boom/vendor/livewire/livewire/src/HydrationMiddleware/PerformActionCalls.php(36): Livewire\\Component->callMethod()
#17 /var/www/boom/vendor/livewire/livewire/src/LifecycleManager.php(89): Livewire\\HydrationMiddleware\\PerformActionCalls::hydrate()
#18 /var/www/boom/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(13): Livewire\\LifecycleManager->hydrate()
#19 /var/www/boom/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(19): Livewire\\Connection\\ConnectionHandler->handle()
#20 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Controllers\\HttpConnectionHandler->__invoke()
#21 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#22 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#23 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#24 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#25 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#27 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#29 /var/www/boom/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#31 /var/www/boom/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/boom/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#33 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#34 /var/www/boom/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#36 /var/www/boom/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#38 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#40 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#41 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#42 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#43 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#44 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#45 /var/www/boom/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#47 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#49 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#51 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#53 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#55 /var/www/boom/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#57 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#59 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#60 /var/www/boom/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#61 {main}

[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'contents.reading_count' in 'order clause' at /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Connection.php:416)
[stacktrace]
#0 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Connection.php(416): PDO->prepare()
#1 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Connection.php(788): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Illuminate\\Database\\Connection->runQueryCallback()
#3 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\\Database\\Connection->run()
#4 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2735): Illuminate\\Database\\Connection->select()
#5 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2724): Illuminate\\Database\\Query\\Builder->runSelect()
#6 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3278): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#7 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2723): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#8 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(717): Illuminate\\Database\\Query\\Builder->get()
#9 /var/www/boom/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(701): Illuminate\\Database\\Eloquent\\Builder->getModels()
#10 /var/www/boom/vendor/power-components/livewire-powergrid/src/Traits/WithExport.php(185): Illuminate\\Database\\Eloquent\\Builder->get()
#11 /var/www/boom/vendor/power-components/livewire-powergrid/src/Traits/WithExport.php(236): App\\Http\\Livewire\\admin\\contents\\ContentsTable->prepareToExport()
#12 /var/www/boom/vendor/power-components/livewire-powergrid/src/Traits/WithExport.php(195): App\\Http\\Livewire\\admin\\contents\\ContentsTable->export()
#13 /var/www/boom/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Http\\Livewire\\admin\\contents\\ContentsTable->exportToXLS()
#14 /var/www/boom/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/boom/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /var/www/boom/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /var/www/boom/vendor/livewire/livewire/src/ComponentConcerns/HandlesActions.php(149): Illuminate\\Container\\BoundMethod::call()
#18 /var/www/boom/vendor/livewire/livewire/src/HydrationMiddleware/PerformActionCalls.php(36): Livewire\\Component->callMethod()
#19 /var/www/boom/vendor/livewire/livewire/src/LifecycleManager.php(89): Livewire\\HydrationMiddleware\\PerformActionCalls::hydrate()
#20 /var/www/boom/vendor/livewire/livewire/src/Connection/ConnectionHandler.php(13): Livewire\\LifecycleManager->hydrate()
#21 /var/www/boom/vendor/livewire/livewire/src/Controllers/HttpConnectionHandler.php(19): Livewire\\Connection\\ConnectionHandler->handle()
#22 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\\Controllers\\HttpConnectionHandler->__invoke()
#23 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#24 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#25 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#26 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#27 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#29 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#31 /var/www/boom/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#33 /var/www/boom/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/boom/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#35 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#36 /var/www/boom/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#38 /var/www/boom/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#40 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#42 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#43 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#44 /var/www/boom/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#45 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#46 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#47 /var/www/boom/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#49 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#51 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#53 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#55 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#57 /var/www/boom/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#59 /var/www/boom/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#61 /var/www/boom/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#62 /var/www/boom/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#63 {main}
"} 


 ```

**Comment by marineusde** [comment] 2023-09-06 10:52
I cant reproduce it, I tryed it with V4.9.0. Here is my code, maybe it helps:

```
public function datasource(): null|QueryBuilder|EloquentBuilder
{
    return TableOne::select(
        [
            'table_one.*',
            DB::raw("
               (
                 SELECT count(*)
                 FROM `table_two`
                 WHERE `table_two`.`table_one_id` = `table_one`.`id`
               ) AS `foo_count`")
        ]);

    /**
     * @return array<int, Column>
     */
    public function columns(): array
    {
        return $this->setColumnArray([
            Column::make('Name', 'name', 'table_one.name')
                ->sortable(),

            Column::make('Foo', 'foo_count', 'foo_count')
                ->sortable(),
        ]);
    }
}
```

**Comment by luanfreitasdev** [comment] 2024-01-20 13:06
I believe this issue has already been resolved or forgotten so I will close it.

Thanks

**Closed as completed by luanfreitasdev** 2024-01-20 13:06 UTC
