### ISSUE TITLE
Toggle off but cannot toggle on

### ISSUE THREAD

**Issue by thetwopct** [Power-Components/livewire-powergrid#48] opened 2021-08-12 06:47 UTC
I'm having some issues with is `toggleable()` and wonder if you can help me?

I have a simple `is_active` bool. If true, the toggle works, but if false the toggle does not display properly on load. Flipping between the states without reloading works. 

My code is simple:

```
          Column::add()
                ->title(__('IS ACTIVE'))
                ->field('is_active')
		->toggleable(true, 1, 0)
                ->makeBooleanFilter('is_active', 'Active', 'Inactive'),
```

Here is a video:

https://user-images.githubusercontent.com/10615884/129149887-c834d06c-6250-4651-bd98-0d64376fc86f.mp4

Probably related, butwhen  using the `toggleable()` method that results in numerous errors and warnings in console:

![2021-08-12-134524](https://user-images.githubusercontent.com/10615884/129150333-dd8ad34d-f30c-44c8-bb0b-372fbd75fd5e.jpg)

I am on Version 1.1.7

**Comment by luanfreitasdev** [comment] 2021-08-12 13:09
Hello @thetwopct , which version of alpinejs is on? At the moment it doesn't support ^3

**Comment by luanfreitasdev** [comment] 2021-08-13 22:36
@thetwopct .

What is your primary key? Currently it gets search for the 'id' key, if this is the problem, it will soon be solved

**Comment by luanfreitasdev** [comment] 2021-08-20 20:32
Hi @thetwopct

I will close this issue because it had no interaction for 7 days and I was also unable to reproduce the reported error.

If this happens, don't be too excited to reopen again.

Hug.

**Closed by luanfreitasdev** 2021-08-20 20:32 UTC
Labels: bug
