### ISSUE TITLE
Multiselect as attribute in a dynamic filter with WireUI.Select component generates error

### ISSUE THREAD

**Issue by pablomadariaga** [Power-Components/livewire-powergrid#1241] opened 2023-11-05 01:20 UTC
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Uncaught Error: The wire:model value must be an array to use the select as multiselect
![image](https://github.com/Power-Components/livewire-powergrid/assets/69119357/6d509b62-febf-4912-a177-0ddf28e50852)

### PHP Version

8.2.9

### PowerGrid

5.1.9

### Laravel

10.30.1

### Livewire

3.1.0

### Alpine JS

3.13.2

### Theme

Tailwind 3.x, Tailwind 3.x with tailwind/forms

### Describe the bug.

The dynamic filter does not work when selecting options using the WireUI component.
An error is displayed in the console Wire ui error: Uncaught Error: The wire:model value must be an array to use the select as multiselect.

This happens when setting the multiselect attribute of the dynamic filter to true:

### To Reproduce...

```
public function filters(): array
    {
        return [
            Filter::dynamic('customer_name', 'customer_id')
            ->component('select') // <x-select ...attributes/>
            ->attributes([
                // 'class'           => 'min-w-[170px]',
                'async-data'      => route('customers.api'),
                'option-label'    => 'full_name',
                'multiselect'     => true,
                'label'           => __('Customer'),
                'option-value'    => 'id',
                'placeholder'     => __('Select an option'),
                'wire:model.lazy' => 'filters.select.customers'
            ]),...
```

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment] 2024-01-20 13:04
Hello!. Unfortunately, I can't reproduce this bug because it uses third-party packages, it's difficult to provide a quick solution for this and for that reason, I'm closing the issue. 

Thanks

**Closed as completed by luanfreitasdev** 2024-01-20 13:04 UTC
