### ISSUE TITLE
Delete Method Does not work

### ISSUE THREAD

**Issue by ehsantalkhouncheh** [Power-Components/livewire-powergrid#139] opened 2021-11-20 23:33 UTC
1.Delete method doesn't work properly It create get method and nothing happen 
2.Inline editing needs double click instead of click

**To Reproduce**
its fresh laravel and powergrid

**Laravel version (exactly):**
8.73.1
 
**Alpine version:**
3.0.6

**Theme:**
- [x] Tailwind 
   - Version: 2.2.2

**Screenshots** (***This helps to understand better***)

**Do you have any idea how we can fix it?**

**Comment by ehsantalkhouncheh** [comment] 2021-11-21 12:02
Hi @luanfreitasdev ,
FYI , it seems delete method calls show method instead of destroy method for some reason

**Comment by luanfreitasdev** [comment] 2021-11-21 12:23
Hello @ehsantalkhouncheh , can you show the html of the generated button?

**Comment by ehsantalkhouncheh** [comment] 2021-11-21 13:24
Hello @luanfreitasdev ,

`<form target="_blank" action="http://localhost/component/2" method="delete">
    <input type="hidden" name="_method" value="delete"> 
    <input type="hidden" name="_token" value="1HIu6bpgu9V84fqOG1GfbxTH1ru035nrKg4bQBNY">
    <button type="submit" class="btn btn-danger">
        Delete
    </button>
</form>`

**Comment by ehsantalkhouncheh** [comment] 2021-11-21 13:28
![Screenshot from 2021-11-21 14-27-06](https://user-images.githubusercontent.com/75850620/142763770-6cb113e8-4f74-42fa-ae67-010143067ac8.png)

**Comment by ehsantalkhouncheh** [comment] 2021-11-21 13:51
But result after press delete button is :
![Screenshot from 2021-11-21 14-50-39](https://user-images.githubusercontent.com/75850620/142764542-2a18d64d-9569-4a22-8b2e-bfae151bde1a.png)

**Comment by luanfreitasdev** [comment] 2021-11-21 14:15
Got it... Can you test this version please?

`composer require power-components/livewire-powergrid dev-when `

**Comment by ehsantalkhouncheh** [comment] 2021-11-21 15:22
I tried it and i have new issue now 
![Screenshot from 2021-11-21 16-21-42](https://user-images.githubusercontent.com/75850620/142767990-df7a7c97-a925-4435-8ccc-45caabed28a9.png)

**Comment by luanfreitasdev** [comment] 2021-11-21 15:38
run: `php artisan vendor:publish --tag=livewire-powergrid-views`

**Comment by ehsantalkhouncheh** [comment] 2021-11-21 15:54
I did it and i ran php artisan optimize:clear still same issue :(

**Comment by luanfreitasdev** [comment] 2021-11-21 16:04
It's probably cache... because on this branch this file that gave an error doesn't have the same characteristics

**Comment by luanfreitasdev** [comment] 2021-11-21 16:05
If you can remove the resources folder and leave only composer's.

**Comment by ehsantalkhouncheh** [comment] 2021-11-22 10:43
I deleted whole project and create new one and with current version it works fine so the queastion is i should master version or current version that you send it to me (dev-when) thanks in advance.

BR,
Ehsan

**Comment by luanfreitasdev** [comment] 2021-11-22 11:18
Hi,

I must release a release this week with the method post fix. 

About displaying the message, it will be optional in this version, for example you can put this in your powergrid class which will show it again:
`public bool $showDefaultMessage = true;`

**Comment by ehsantalkhouncheh** [comment] 2021-11-22 11:35
Hi @luanfreitasdev ,

First of all thank you so much for quick reply and yes i tested it and it works fine so in new relaese you will fix datetimepicker show up and also problem that we have about updating create_at after each page refresh am i right?
I gonna use your package for production do you think it would be ready for this perpose?

BR,
Ehsan

**Comment by luanfreitasdev** [comment] 2021-11-22 14:41
What created_at problem are you talking about ?

**Comment by ehsantalkhouncheh** [comment] 2021-11-22 19:37
when you refresh the page powergrid update created_at field for all rows automatically

**Comment by ehsantalkhouncheh** [comment] 2021-11-23 13:17
My update method is empty now I added the livewire component that created by powergrid and thats it i did nothing else and all my controller methods are empty at the moment so every time that i refresh the page powergrid shows me the diffrent created_at value, it seems powegrid update create_at automatically with current time

**Comment by luanfreitasdev** [comment] 2021-11-23 13:33
How can you make a video showing how it works and also show how to assemble the created_at field?

**Comment by ehsantalkhouncheh** [comment] 2021-11-24 01:11
Hi @luanfreitasdev ,

It seems created_at field doesn't update automatically now but datetime picker doesn't show up in filter area

https://user-images.githubusercontent.com/75850620/143153159-4e1d3497-6f9b-4565-aacb-e9206d7c7c0b.mp4

**Comment by luanfreitasdev** [comment] 2021-11-24 11:32
Hi @ehsantalkhouncheh 

Is there any error on the console?

**Comment by ehsantalkhouncheh** [comment] 2021-11-25 11:33
Hi @luanfreitasdev ,

It seems **composer require power-components/livewire-powergrid dev-when** package doesnt exist anymore  and main package still has problem with delete method i mean it calls show method instead of destroy

**Comment by luanfreitasdev** [comment] 2021-11-25 13:58
Hello. Ehsan 

I put it on this branch just to test the functionality. Today I will review and release the release with the fix.

**Comment by luanfreitasdev** [comment] 2021-11-26 19:58
@ehsantalkhouncheh . 

I will close this issue because the main issue has already been resolved. About the creation date filter you can open another issue for us to investigate further. Apparently it might be some conflict with js. But I couldn't reproduce it.

thanks

**Closed by luanfreitasdev** 2021-11-26 19:58 UTC
Labels: bug
