### ISSUE TITLE
[Bug - V5]: RulesController::recoverFromAction(): Argument #1 ($row) must be of type Illuminate\Database\Eloquent\Model|stdClass|array, string given

### ISSUE THREAD

**Issue by jigapate** [Power-Components/livewire-powergrid#1125] opened 2023-09-03 08:11 UTC
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes,  

```
PowerComponents\LivewirePowerGrid\Components\Rules\RulesController::recoverFromAction(): Argument #1 ($row) must be of type Illuminate\Database\Eloquent\Model|stdClass|array, string given, called in /var/www/html/storage/framework/views/1cb0d8b37a8cd8f8415f56deda5ecd6f.php on line 155
```

### PHP Version

8.2.9

### PowerGrid

v5.0.0-beta

### Laravel

10.21

### Livewire

3.0

### Theme

Bootstrap

### Describe the bug.

I have Laravel 10 installation with MongoDB database connection,
I have upgraded to Livewire 3 and Powergrid 5 beta,

When I called the users table, it threw TypeError,

```
PowerComponents\LivewirePowerGrid\Components\Rules\RulesController::recoverFromAction(): Argument #1 ($row) must be of type Illuminate\Database\Eloquent\Model|stdClass|array, string given, called in /var/www/html/storage/framework/views/1cb0d8b37a8cd8f8415f56deda5ecd6f.php on line 155

```

![image](https://github.com/Power-Components/livewire-powergrid/assets/11524768/29028a21-0d8c-4e2b-a4b2-eafc2de0a0ad)

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment] 2023-09-03 14:32
Hello!. Did it work with MongoDB before?

**Comment by jigapate** [comment] 2023-09-03 14:34
> Hello!. Did it work with MongoDB before?

Yes, it worked before upgrade to 5.0 beta

**Comment by jigapate** [comment] 2023-09-04 12:17
Below is a screenshot of queries that were sent to DB,

![image](https://github.com/Power-Components/livewire-powergrid/assets/11524768/d9149553-e960-40f4-8adb-1eb071df675e)

And below screenshot is about arguments,

![image](https://github.com/Power-Components/livewire-powergrid/assets/11524768/73569519-55a6-4c9e-9412-8ab42bafcc9c)

**Comment by jigapate** [comment] 2023-09-04 12:32
Update....
When I copied the complete code from https://github.com/Power-Components/livewire-powergrid/blob/5.x/resources/views/components/table.blade.php to my local file, it worked well.

I guess, something wrong with first arguments in new install of Powergrid,

**Comment by luanfreitasdev** [comment] 2023-09-07 21:28
For now, I'm going to defer support for this to version 5 as I couldn't reproduce this problem because I don't use MongoDB. If you want to send a Pull Request you will be welcome.

**Comment by luanfreitasdev** [comment] 2023-12-05 18:07
I don't know if this is still an active bug. I'm closing for this reason. Is there anything we can work on it?

Thanks!

**Closed as completed by luanfreitasdev** 2023-12-05 18:07 UTC
Labels: bug
