### ISSUE TITLE
[Bug]: When we delete one or more filters the other filters duplicate their options

### ISSUE THREAD

**Issue by amedeopro** [Power-Components/livewire-powergrid#1024] opened 2023-06-08 16:42 UTC
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

yes, there are some errors in console:

Uncaught (in promise) 
Object { isFromCancelledTransition: true }

Uncaught (in promise) TypeError: i is not a function
    carry module.esm.js:1053

### PHP Version

8.1.10

### PowerGrid

4.6.3

### Laravel

9.52.8

### Livewire

2.12.3

### Alpine JS

3.12.0

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When we clear one or more filters the options in the other filters are duplicated. We use WireUI x-select in filters function.

### To Reproduce...

set two or more x-select filters and try to clear  one.  The table is refreshed and options are duplicated.

### Extra information

```markdown
Filter::dynamic('location', 'location')
                ->component('select')
                ->attributes([
                    'class'           => 'min-w-[250px]',
                    'option-label'    => 'location',
                    'option-value'    => 'location',
                    'placeholder'     => 'Location',
                    'options'         => Device::select('location')->groupBy('location')->get()->toArray(),
                    'wire:model.lazy' => 'filters.select.location'
                ]),
Filter::dynamic('smil_enabled', 'smil_enabled')
                ->component('select')
                ->attributes([
                    'class'           => 'min-w-[150px]',
                    'option-label'    => 'name',
                    'option-value'    => 'smil_enabled',
                    'placeholder'     => 'Smil',
                    'options'         => [
                            ['name' => 'Active',  'smil_enabled' => 1],
                            ['name' => 'Deactivated',  'smil_enabled' => 0],
                    ],
                    'wire:model.lazy' => 'filters.select.smil_enabled'
                ]),
```

**Comment by amedeopro** [comment] 2023-06-13 06:47
@luanfreitasdev can you help me?

**Comment by luanfreitasdev** [comment] 2023-06-13 09:37
hello!. I still haven't been able to reproduce this problem. Could you send a video?

**Comment by amedeopro** [comment] 2023-06-13 11:05
Hello @luanfreitasdev  , thanks for your reply, here is the link to the video  https://we.tl/t-Ih4N5as1M3 

Thank you

**Comment by amedeopro** [comment] 2023-06-14 13:14
@luanfreitasdev hello, did you see the video?

**Comment by luanfreitasdev** [comment] 2023-06-14 14:35
Yes, but I can't reproduce the problem. Can you load a git project containing the same behavior?

**Comment by amedeopro** [comment] 2023-06-15 11:16
We have tried with demo table, we have inserted this filters:
```
 Filter::dynamic('email', 'email')
                ->component('select')
                ->attributes([
                    'option-label'    => 'name',
                    'option-value'    => 'value',
                    'placeholder'     => 'Email',
                    'options'         => [
                        ['name' => 'esteban.schoen@example.org',  'value' => 'esteban.schoen@example.org'],
                        ['name' => 'wyman.effie@example.org',  'value' => 'wyman.effie@example.org'],
                        ['name' => 'emil.hansen@example.com',  'value' => 'emil.hansen@example.com'],
                    ],
                    'wire:model.lazy' => 'filters.select.email'
                ]),
            Filter::dynamic('laracon', 'laracon')
                ->component('select')
                ->attributes([
                    'option-label'    => 'name',
                    'option-value'    => 'value',
                    'placeholder'     => 'Laracon Visitor?',
                    'options'         => [
                        ['name' => 'Yes',  'value' => 'yes'],
                        ['name' => 'No',  'value' => 'no'],
                    ],
                   'wire:model.lazy' => 'filters.select.laracon'
                ]),
```
but the results are the same...

FIY: if you try to set only one dynamic filters it works correctly, but if you set the second dynamic filters you get the same errors.

Sorry but i can't publish publically our git repo.

@luanfreitasdev

**Comment by amedeopro** [comment] 2023-06-19 08:41
@luanfreitasdev have you something news ?

**Comment by luanfreitasdev** [comment] 2023-06-22 23:39
Hello!. I tried using a select component and another input and it worked normally. I believe it's a bug in select and not how PowerGrid works with filters. Do you use wire-ui? Try using another select component, believed to be a bug in the component.

**Comment by luanfreitasdev** [comment] 2024-01-20 13:05
Hello!. Unfortunately, I can't reproduce this bug because it uses third-party packages, it's difficult to provide a quick solution for this and for that reason, I'm closing the issue. 

Thanks

**Closed as completed by luanfreitasdev** 2024-01-20 13:05 UTC
