### ISSUE TITLE
Table data and pagination are sometimes not updated in responsive tables after the search input has been used

### ISSUE THREAD

**Issue by lsmedia** [Power-Components/livewire-powergrid#1638] opened 2024-08-10 12:44 UTC
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes

Mozilla Firefox 115.12.0esr (64-Bit):
```
Uncaught TypeError: this.endComment is null
    **appendChild** http://lima.dev.lsm.local/build/assets/app-3826c172.js:56
```

Chromium 126.0.6478.114 (64 bit, Official Build) 
```
livewire.esm.js:6948 Uncaught 
TypeError: Cannot read properties of undefined (reading 'before')
    at G.**appendChild** (livewire.esm.js:6948:25)
```

### PHP Version

8.2.17 (cli)

### PowerGrid

5.8.1

### Laravel

10.48.14

### Livewire

3.5.1

### Alpine JS

3.13.10

### Theme

Tailwind 3.x

### Describe the bug.

For responsive tables (`Responsive::make()` set in `setUp()`) with Tailwind theme, the pagination is not updated correctly after the global search (`Header::make()->showSearchInput()` set in `setUp()`) has been used.

The table content is (partially) updated, but the pagination remains unchanged - even if fewer hits were found and the display of the number of hits and also the page links would have to be updated.

Surprisingly, the error only occurs if the search term is expanded, i.e. if an additional character is entered. If a character is removed, the entire pagination is reloaded correctly. It should also be noted that the error does not occur if there is only one page and the pagination is omitted completely. In this case, too, everything is updated correctly.

### To Reproduce...

- Create a responsive table with global search function in the header and tailwind theme.
- Load data so that more than 2 pages and therefore also the pagination is displayed.
- Use the search function to limit the number of hits.
- The pagination is not updated until the search has been narrowed down so that all search results can be displayed on one page.

### Extra information

In my opinion, the message in the console "Error in function `appendChild`" indicates that Livewire is having problems morphing the component. ~When I load the page source into an HTML validator, I can see that the HTML becomes invalid due to the enclosing `DIV` around `TH` (in [resources/views/components/checkbox-all.blade.php](https://github.com/Power-Components/livewire-powergrid/blob/5.x/resources/views/components/checkbox-all.blade.php)), because the `DIV` must not be directly in a `TABLE`.~

~Can there be a coherence with the described error?~

Edit: I would like to rule out the checkbox blade as the cause. After I deactivated checkboxes completely in the table, the message is no longer displayed in the HTML validator, but the error in the pagination still exists.

**Comment by lsmedia** [comment] 2024-08-10 14:39
I think I have found the possible cause. Apparently it is the wire:key in the [expand-container blade](https://github.com/Power-Components/livewire-powergrid/blob/5.x/resources/views/components/expand-container.blade.php).

As soon as I remove the key or replace it with something randomly generated (e.g. `'expand-' . rand()` ), the error in the console disappears and the table and pagination are updated as expected after narrowing down the number of hits via the search input in the header.

Here's the code in question:

```
<tbody
    x-cloak
    expand
    wire:key="{{ 'expand-' . $rowId }}"               <--- I have removed this key
    x-show="hasHiddenElements"
>

    ...

</tbody>
```

I did not notice any further negative effects after the key was removed.
Can someone please try to reproduce the error described? Do you see any negative effects from removing the key?

**Comment by Uhasith** [comment] 2024-08-13 08:25
Same here. When adding `Responsive::make()` table has some UI glitches and functionality issues

**Comment by luanfreitasdev** [comment] 2024-08-13 22:15
Related: https://github.com/Power-Components/livewire-powergrid/issues/1580

**Comment by Uhasith** [comment] 2024-08-14 02:39
I did run a `composer update ` and changed `'inject_morph_markers' => false` inside the livewire config file. You closed my previous issue about this. But when i add `Responsive::make()->fixedColumns('id', 'name', Responsive::ACTIONS_COLUMN_NAME)` the action columns are not fixed. They Hide on small screens. How can i fix this? I want always to show action columns no matter screen is large or small. @luanfreitasdev  


<img width="1430" alt="Screenshot 2024-08-14 at 08 06 18" src="https://github.com/user-attachments/assets/692bdd30-4828-4a5a-991b-1679891222c5">

**Comment by luanfreitasdev** [comment] 2024-08-14 02:43
A fix will be released tomorrow. Thanks you

**Comment by Uhasith** [comment] 2024-08-14 02:47
Yeah, i found a temporary solution. I need to add `->fixedOnResponsive()`  to my column. Then it remains fixed on the small screens too. but not sure if this is a good way to do that. `Column::action('Action')->fixedOnResponsive(),`. Also please update the Documentation about this if you can. @luanfreitasdev   ❤️

**Comment by lsmedia** [comment] 2024-08-14 08:17
> Related: #1580

Thank you @luanfreitasdev for drawing my attention to Issue #1580 . It looks like the two issues are indeed related.

In the other issue you write that it would take a lot of effort to correct the error. Would you please give me a brief overview of which code needs to be refactored and why exactly the injection of the markers triggers this error?

I use a lot of Livewire components in my project and will probably have to rebuild a lot if I deactivate the morph markers. I also think that the morph markers are a very useful function to keep the code as elegant and clear as possible. With frequent use of conditional templates, I think the code gets very ugly if everything has to be encapsulated. 

Therefore, I would be very interested in helping to implement the necessary changes to your Powergrid project. It might be the same amount of work, but would be of greater benefit to everyone.

**Comment by Uhasith** [comment] 2024-08-14 08:20
Yeah I'm getting this console error when trying to use paginate of the Table

`module.esm.js:277 Uncaught TypeError: Cannot read properties of undefined (reading 'before')`

**Comment by lsmedia** [comment] 2024-08-14 08:25
Thank you @Uhasith  for the information. It is the same message that I am receiving.

My question was addressed to @luanfreitasdev , as he has obviously already looked at the issue in a different way. See #1580 .

**Comment by Uhasith** [comment] 2024-08-14 08:26
Hi @luanfreitasdev,

Thank you for your prompt action on addressing the issues related to the “Inject morph markers” feature in Livewire. I appreciate the temporary fix by disabling the feature in the configuration.

However, considering the potential impact on future packages built using Livewire, I believe it would be more sustainable to explore an alternative solution that doesn’t involve changing the Livewire configuration. Disabling inject_morph_markers globally could lead to unforeseen issues with other packages that rely on this feature, so it might be better to address the root cause directly.

Would it be possible to consider a different approach that allows us to maintain the current configuration? Perhaps we could look into specific refactoring or adjustments that could resolve the problem without altering the default behavior of Livewire. This way, we can ensure compatibility and stability for all future developments.

Let me know your thoughts, and I’m happy to discuss potential solutions further.

Thanks again for your efforts!

**Comment by luanfreitasdev** [comment] 2024-08-19 17:23
Hello, everyone!

The fix was simpler than I thought. 😃

https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.10.2

thanks

**Closed as completed by luanfreitasdev** 2024-08-19 17:23 UTC
