### ISSUE TITLE
Duplicate Action Buttons after changing Per Page count.

### ISSUE THREAD

**Issue by JF-626164** [Power-Components/livewire-powergrid#215] opened 2022-01-06 16:58 UTC
First of all, did you see if your problem has happened to other people before?
- [x] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**

I have the "->showPerPage(25)" in the setup and I have two row action buttons, I've noticed that when I change the Per Page count from 25 to 10, those 10 rows all have duplicate buttons.

**To Reproduce**
* Got to ..

**Laravel version (exactly)** 

8.78.0

**Livewire version (exactly)**

v2.8.2

**AlpineJS:** 

8.1.4

**Theme:**
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [x] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)
![PowergridButtonsBug](https://user-images.githubusercontent.com/74377418/148420441-9376bfa5-ea21-45b3-9776-cfd3958422a8.PNG)

**Comment by luanfreitasdev** [comment] 2022-01-06 20:44
Hi @JF-626164 , 

I tried to play and I couldn't simulate the error using powergrid-demo, can you show a video with the step you made?

thanks

**Comment by JF-626164** [comment] 2022-01-07 13:24
https://user-images.githubusercontent.com/74377418/148549814-169bbd9a-a260-44c1-8f38-94eca05d4b87.mp4

**Comment by luanfreitasdev** [comment] 2022-01-12 19:45
Thanks for submitting, but I still couldn't reproduce this problem

**Comment by luanfreitasdev** [comment] 2022-01-29 12:12
Unfortunately I couldn't reproduce this problem, if you can update to the latest version and test it again. For now I will close it.

Thanks

**Closed by luanfreitasdev** 2022-01-29 12:12 UTC
Labels: bug
